I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 195, in script
    Ivanka "Oh my, a new face! Welcome, traveler."
Exception: Sayer 'Ivanka' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 195, in script
    Ivanka "Oh my, a new face! Welcome, traveler."
  File "C:\Users\Admin\Downloads\renpy-8.3.3-sdk\renpy\ast.py", line 2573, in execute
    Say.execute(self)
  File "C:\Users\Admin\Downloads\renpy-8.3.3-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Admin\Downloads\renpy-8.3.3-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Ivanka' is not defined.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.3.24111502
RietmanOrigins 1.0
Sat Mar  8 09:55:49 2025
